---
title: "producthunt-exercise_zhangjiabin"
author: "Zhangjiabin"
date: "2019/2/15"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggthemes)
library(ggplot2)
library(lubridate)
knitr::opts_chunk$set(echo = TRUE)
df_topics <- readr::read_csv("~/Desktop/producthunt-exercise/DATA/AllTopics.csv")
df_posts <- readr::read_csv("~/Desktop/producthunt-exercise/DATA/PostsForAnalysis.csv")
df_users <- readr::read_csv("~/Desktop/producthunt-exercise//DATA/UsersForAnalysis.csv")
```

## ??????
[Product Hunt](https://www.producthunt.com) ??????????????? PH ??? ????????????????????????????????????????????????????????????????????????????????????, ???????????????????????????????????????????????????????????? ?????????????????????????????????????????? PH ???????????????????????????????????????????????? Product Hunt API ????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
## ????????????
### 1 ?????????????????????
PH ?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????? (num_followers) ???????????? ???????????????????????????????????????20??????????????????????????????????????????????????????????????????????????????????????????????????????

```{r question1, echo=FALSE}

df_topics %>% 
  group_by(name) %>% 
  mutate_at(vars("num_posts", "num_followers"), as.numeric) %>%
  summarise(posts = sum(num_posts) , followers = sum(num_followers,na.rm = TRUE)) %>% 
  arrange(desc(posts),desc(followers)) %>% 
  head(20) %>% 
  ggplot(mapping =aes(x=reorder(name,-posts),y= posts)) +
  geom_bar(stat = "identity",alpha = 1/5,width= 0.2,colour="#000099")+
  geom_point(mapping = aes(size = followers))

```

###2 ?????????????????????????????????

????????????????????? (votes_count) ???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

??????: ?????????????????????(dttm)???????????? ?lubridate::year()
```{r question2, echo=FALSE}
df_posts %>% 
  mutate(year = year(date)) %>% 
  group_by (year,time_of_day) %>% 
  summarise(votes = sum(votes_count,na.rm = TRUE)) %>% 
  ggplot(mapping =aes(x=year,y= votes,color = time_of_day))+
  geom_bar(stat = "identity",alpha = 1/5,width= 0.2,position='dodge')

```
###3 ??????????????????????????????

???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????30????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????20???????????????


```{r question3, echo=FALSE}
df_votes = df_posts %>% 
  group_by(user_id) %>% 
  summarise(vote_averge = mean(votes_count))

df_user_posts = merge(df_votes, df_users,by='user_id' ,all=TRUE, sort=TRUE)
df_user_posts %>% 
  filter(posts_count>=30) %>% 
  arrange(desc(vote_averge)) %>% 
  head(20) %>% 
  ggplot(mapping =aes(x=reorder(name,vote_averge),y= vote_averge)) +
  geom_bar(stat = "identity",alpha = 1/5,width= 0.2,colour="#000099")+
  coord_flip()+
  geom_point(mapping = aes(size = posts_count))
  

```
###4 ??????????????????????????????

?????????????????? PH ??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????? tech ?????????????????????????????????????????????????????????????????????10????????????

???????????????????????????????????? ?tidyr::gather()
```{r question4, echo=FALSE}

```



